### ISSUE TITLE
[Feature Request] Add support for Python 3.11

### ISSUE THREAD

**Issue by ca-simone-chiorazzo** [apache/pulsar-client-python#100]
Hi folks,

python 3.11 is out since a while and it brings a lot of nice improvements especially related to performance. Is there any plan to add support for it?

**Comment by BewareMyPower** [comment]
The 3.1.0 that is released in progress adds the support for Python 3.11, you can try the wheels here: https://lists.apache.org/thread/lyzyyg9yhwc836trv0dhdgq23bym4som

**Comment by BewareMyPower** [comment]
Close this issue by the formal Python client 3.1.0 release: https://lists.apache.org/thread/nj8lhd2sk4073lkvj53yj9dv9y885nm2
