### ISSUE TITLE
Please upgrade pulsar c++ client to v3.1.1+ and release a new version

### ISSUE THREAD

**Issue by Maslino** [apache/pulsar-client-python#104]
pulsar c++ client fixed a critical segment fault bug:

[Fix segfault caused by socket I/O on a closed io_service](https://github.com/apache/pulsar-client-cpp/pull/168)

We have the same problem in our production environment. It would be great to upgrade the c++ client as soon as possible.

**Comment by RobertIndie** [comment]
Hi, We have already raised the new release for python client 3.1.0 which depends on the C++ client 3.1.2. The vote has been passed and the release will be announced soon. Please check this email: https://lists.apache.org/thread/lyzyyg9yhwc836trv0dhdgq23bym4som

**Comment by BewareMyPower** [comment]
The Python client 3.1.0 that depends on the C++ client 3.2.0 is present now: https://lists.apache.org/thread/nj8lhd2sk4073lkvj53yj9dv9y885nm2
