### ISSUE TITLE
CRC32C SSE4.2 is disabled for macOS universal build

### ISSUE THREAD

**Issue by BewareMyPower** [apache/pulsar-client-python#14]
See outputs from https://github.com/apache/pulsar-client-python/actions/runs/3236234222/jobs/5301759237

> /Users/runner/work/pulsar-client-python/pulsar-client-python/.pulsar-mac-build/cpp/apache-pulsar-client-cpp-3.0.0/lib/checksum/crc32c_sse42.cc:42:2: warning: "BOOST_ARCH_X86_64 is not defined, CRC32C SSE4.2 will be disabled" [-W#warnings]
#warning "BOOST_ARCH_X86_64 is not defined, CRC32C SSE4.2 will be disabled"

> /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: x86_64 file: /Users/runner/work/pulsar-client-python/pulsar-client-python/.pulsar-mac-build/cpp/install/lib/libpulsar.a(Log4cxxLogger.cc.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: x86_64 file: /Users/runner/work/pulsar-client-python/pulsar-client-python/.pulsar-mac-build/cpp/install/lib/libpulsar.a(crc32c_arm.cc.o) has no symbols
-- Up-to-date: /Users/runner/work/pulsar-client-python/pulsar-client-python/.pulsar-mac-build/cpp/install/lib/libpulsar.a
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: x86_64 file: /Users/runner/work/pulsar-client-python/pulsar-client-python/.pulsar-mac-build/cpp/install/lib/libpulsar.a(Log4cxxLogger.cc.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: x86_64 file: /Users/runner/work/pulsar-client-python/pulsar-client-python/.pulsar-mac-build/cpp/install/lib/libpulsar.a(crc32c_arm.cc.o) has no symbols

**Comment by BewareMyPower** [comment]
If we cannot support SSE 4.2 for ARM64, we should not build universal binaries for Intel-based macOS users. i.e. change the `ARCH` to `x86_64`. 

https://github.com/apache/pulsar-client-python/blob/ddb1229c92d85435278831ea4e00bc63867a7548/pkg/mac/build-pulsar-cpp.sh#L46

WDYT? @merlimat

**Comment by merlimat** [comment]
When compiling for multiple archs, the compiler is doing multiple passes. It's normal to not have SSE 4.2 in ARM, so we can ignore this warning message.

**Comment by BewareMyPower** [comment]
Thanks for your explanation. Close it.
