### ISSUE TITLE
Error message should be f-string, but is just string

### ISSUE THREAD

**Issue by ben-kearney** [apache/pulsar-client-python#144]
https://github.com/apache/pulsar-client-python/blob/ba99cd5f372ab645bbb12239dad53668b10075a9/pulsar/schema/schema_avro.py#L93-L94

Since this is a string and not an f-string, we are unable to see which topic+version is having an issue, and we are unable to see the error.

**Comment by BewareMyPower** [comment]
It looks like a simple fix, would you like to open a PR for it?
