### ISSUE TITLE
Pulsar Python Client. Can it work in Layer 7 protocols?

### ISSUE THREAD

**Issue by olsenpabu** [apache/pulsar-client-python#149]
I just want to ask if somehow we can use the python client library to work with Layer 7 protocols to use Application Load Balancers as endpoints.

**Comment by shibd** [comment]
Now support HTTP protocol to do `lookup`. Do you want to produce/consume messages using the HTTP protocol as well?

**Comment by BewareMyPower** [comment]
No. It does not support.

**Comment by olsenpabu** [comment]
Thank you for feedback. Will close the issue
