### ISSUE TITLE
Not available for Python 3.12

### ISSUE THREAD

**Issue by ullebe1** [apache/pulsar-client-python#156]
It seems like there is no available versions for Python 3.12 in PyPI. When can we expect that to be available?

Logs from a CI run of a container based on `docker.io/library/python:3.12` 
```
 > [8/8] RUN pip install -r requirements.txt:
2.857 ERROR: Could not find a version that satisfies the requirement pulsar-client>=3.1.0 (from versions: none)
2.858 ERROR: No matching distribution found for pulsar-client>=3.1.0
```
This worked fine with Python 3.11.

**Comment by rongxin-liu** [comment]
We are running into the same issue with Python 3.12.
