### ISSUE TITLE
[Bug] Memory issue using Record with Array 

### ISSUE THREAD

**Issue by Vincouux** [apache/pulsar-client-python#173]
### Version
OS: Ubuntu 22.04
Python: 3.10.2
Pulsar: pulsar-client==3.2.0

### Minimal reproduce step
```python3
from pulsar.schema import Record, Array, Integer

class A(Record):
    a = Array(Integer(), required=False, default=[])

# Create a first instance of object A
a = A()
a.a # Correctly show empty list
a.a.append(1) # Adding an integer
a.a # Correctly showing list with single element 1 inside

# Instanciating a second object A
b = A()
b.a # Incorrectly show list with single element 1
```

### What did you expect to see?
I expected the A class not to re-use the previous reference to the list. 

### What did you see instead?
As a developer, instantiating a fresh object in Python generally means it's built from scratch. Therefore, no reference to previously built objects should be used.

**Comment by gromsterus** [comment]
1. `list` is a mutable data structure in Python. In your example, new instances of class `A` reference and modify the same list object in memory. You can read more about this [here](https://www.geeksforgeeks.org/use-mutable-default-value-as-an-argument-in-python/). 

2. The `Record` class has quite simple logic for working with `default`. As a solution, you could add a `default_factory` implementation, like [here](https://docs.python.org/3/library/dataclasses.html#dataclasses.field). Or, do not use `default` and instantiate objects of the `Record` class by passing arguments manually.

**Comment by Vincouux** [comment]
I decided to remove default and making every mutable data structures required as a solution ! Thanks for the answer.
