### ISSUE TITLE
What is the latest python version currently supported by this? I did not find it

### ISSUE THREAD

**Issue by sunheyi6** [apache/pulsar-client-python#175]
i use pthon 3.12.1,but it happened error
```python
C:\Users\10618>C:\Users\10618\AppData\Local\Programs\Python\Python312\python.exe --version
Python 3.12.1
C:\Users\10618>C:\Users\10618\AppData\Local\Programs\Python\Python312\python.exe -m pip install pulsar-client
ERROR: Could not find a version that satisfies the requirement pulsar-client (from versions: none)
ERROR: No matching distribution found for pulsar-client
```

**Comment by merlimat** [comment]
For current release we only support up to Python 3.11. The support for 3.12 was already merged in https://github.com/apache/pulsar-client-python/pull/160 . It will be released in the next week.

**Comment by sunheyi6** [comment]
ok i support we should show the support python version in the readme

**Comment by BewareMyPower** [comment]
Yes, the README should be updated.

**Comment by mingtai101** [comment]
I am running python 3.12.1 and getting the same error  (December 29, 2023).  Does pulsar-client support 3.12 now??

**Comment by BewareMyPower** [comment]
3.4.0, which is in vote currently, will support Python 3.12.
