### ISSUE TITLE
Version 2.10.2 on pypi missing macos wheels

### ISSUE THREAD

**Issue by jaysonsantos** [apache/pulsar-client-python#20]
Hi there, I'd like to report that the new release on pypi `2.10.2` does not have the macos wheels nor the source package to build from.

**Comment by merlimat** [comment]
@jaysonsantos The release process for wheel files have been automated in this new repo and we'll have consistent wheel releases for all the supported platforms. 

We're planning to do a 3.0.0 release of Python client very soon. You can find some pre-release binaries here: https://github.com/merlimat/pulsar-client-python/actions/runs/3260182852

**Comment by erichare** [comment]
@merlimat @jaysonsantos I believe we can close this issue as the Mac wheels were uploaded a couple days later, and are available here: https://pypi.org/project/pulsar-client/2.10.2/#files

**Comment by merlimat** [comment]
The 3.x releases are now all automated in building wheels for all supported platforms.
