### ISSUE TITLE
3.5.0 release?

### ISSUE THREAD

**Issue by Samreay** [apache/pulsar-client-python#207]
It'd be great to get the bug fixes from the C++ client as soon as we can :)

**Comment by BewareMyPower** [comment]
I started a 3.5.0 release candidate last week: https://lists.apache.org/thread/67b1p5kpfx08wq0cy9vjpcq5dyygspw7

However, I found a regression of the C++ client (https://github.com/apache/pulsar-client-cpp/issues/420) two days ago and tried to fix that issue. So we need to fix it and release C++ client 3.5.1 first.

**Comment by BewareMyPower** [comment]
The wheels are available in PyPI now: https://pypi.org/project/pulsar-client/3.5.0/#files
