### ISSUE TITLE
There is a memory leak，I need help

### ISSUE THREAD

**Issue by kansnow** [apache/pulsar-client-python#208]
```
import time
import pulsar
import sys
import gc

client = pulsar.Client('pulsar://localhost:6650')

def connect_to_pulsar():
    producer = None
    try:
        producer = client.create_producer('my-topic')
        producer.send(b'Hello Pulsar!')
    except Exception as e:
        print(f"Connection to Pulsar failed: {e}")
    finally:
        size = sys.getsizeof(client)
        print(f"Memory usage of {client.__class__.__name__} object: {size} bytes")
        if producer:
            producer.close()
        gc.collect()

for _ in range(1000000):
    connect_to_pulsar()
    time.sleep(1)

client.close()
```

there is my code，I am using pulsar-client with version 2.9.1. when I run this code in python3,  Process memory keeps growing.
Where exactly is the problem？

**Comment by merlimat** [comment]
Can you try with latest version 3.4.0? https://pypi.org/project/pulsar-client/

**Comment by kansnow** [comment]
> Can you try with latest version 3.4.0? https://pypi.org/project/pulsar-client/

ok, I'll try upgrading the version

**Comment by kansnow** [comment]
> Can you try with latest version 3.4.0? https://pypi.org/project/pulsar-client/

Thank you very much. I used the top command to check the memory usage of the process. After upgrading the version, the memory did not grow anymore
