### ISSUE TITLE
[feature] Use pybind11 to eliminate the Boost.Python

### ISSUE THREAD

**Issue by BewareMyPower** [apache/pulsar-client-python#24]
See https://github.com/pybind/pybind11#readme

> The main issue with Boost.Python—and the reason for creating such a similar project—is Boost. Boost is an enormously large and complex suite of utility libraries that works with almost every C++ compiler in existence. This compatibility has its cost: arcane template tricks and workarounds are necessary to support the oldest and buggiest of compiler specimens. Now that C++11-compatible compilers are widely available, this heavy machinery has become an excessively large and unnecessary dependency.

**Comment by merlimat** [comment]
Main reason why it was not initially used was to support C++ 98, though Pulsar C++ client has since switched to C++ 11 and there's no more a reason not to use it.

**Comment by tisonkun** [comment]
Cheers!
