### ISSUE TITLE
Provide a way to print package version

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar-client-python#27]
Perhaps `pulasr.__version__` as the idiom.

**Comment by erichare** [comment]
@tisonkun i believe we can close this now, as this has been merged in already. Thanks!

**Comment by tisonkun** [comment]
Thank you @erichare! Maybe you can ask for assign the next time so we can cross-refer the effort :)

**Comment by erichare** [comment]
I’ll try to remember to do that yep :) Thanks!
