### ISSUE TITLE
[Client][python] Build Python client for Windows

### ISSUE THREAD

**Issue by yaalsn** [apache/pulsar-client-python#29]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

I try to build cpp client  with `static` flag, and it seems that link progress will be fail. 

Here is my pr: https://github.com/apache/pulsar/pull/17507/files

```
cmake \
  -B ./build-1 \
  -G "${{ matrix.generator }}" ${{ matrix.arch }} \
  -DBUILD_PYTHON_WRAPPER=ON -DBUILD_TESTS=OFF \
  -DVCPKG_TRIPLET=${{ matrix.triplet }} \
  -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_STATIC_LIB=ON \
  -S .
```

The workflow run is here: 

https://github.com/apache/pulsar/runs/8223165825?check_suite_focus=true#step:12:239

Maybe we need to fix CMakeLists.txt to support the compile. 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Moved to the dedicated repository.

**Comment by BewareMyPower** [comment]
Closed by https://github.com/apache/pulsar-client-python/pull/23
