### ISSUE TITLE
Add CI for build and tests

### ISSUE THREAD

**Issue by BewareMyPower** [apache/pulsar-client-python#4]
See:
- https://github.com/apache/pulsar/blob/0f53c790ff2e3051ebc80aa8d2c9253265725aeb/.github/workflows/pulsar-ci.yaml#L480-L482

The original build and test process is here: https://github.com/apache/pulsar-client-cpp/blob/e145d3532aaf17562eb5c04170632ddd15ee1ea3/run-unit-tests.sh#L61

**Comment by tisonkun** [comment]
One more idea here is that we can add a CI job to verify `pydoctor` generated docs doesn't contain syntax error.

I'm going to follow-up this suggestion in this month.
