### ISSUE TITLE
[python] Pulsar Client package is missing from PyPi for Macosx and Python37

### ISSUE THREAD

**Issue by zbentley** [apache/pulsar-client-python#51]
**Describe the bug**
On PyPi, there are macosx `pulsar-client` wheels for python 38, 39, and 310, but not 37.

Python 3.7 is the most widely used version of Python 3; supporting it should be a priority.

**Comment by tisonkun** [comment]
I'll appreciate it if @zbentley you can pick https://github.com/apache/pulsar/pull/15436 to this new repo :)

**Comment by merlimat** [comment]
We now have the packages for Py 3.7 x86 & arm for MacOS published for all new releases
