### ISSUE TITLE
[Doc] Update the release process about how to release Python client 

### ISSUE THREAD

**Issue by BewareMyPower** [apache/pulsar-client-python#64]

**Comment by merlimat** [comment]
@BewareMyPower We should probably include some scripts to automate the staging of the release, like https://github.com/apache/pulsar-client-cpp/blob/main/build-support/generate-source-archive.sh or https://github.com/apache/pulsar-client-cpp/blob/main/build-support/download-release-artifacts.py

**Comment by BewareMyPower** [comment]
@merlimat Yeah, I have already written some scripts in my local env. I will fix and submit them later.
