### ISSUE TITLE
Windows builds

### ISSUE THREAD

**Issue by Diggsey** [apache/pulsar-client-python#7]
Any possibility of getting windows support for the Pulsar python package?

I've tried building it localy and got pretty far, but ran into issues with matching the python version between boost-python and pulsar-client-python, which I've been unable to resolve.

The C++ client itself builds fine on windows, so I don't think there should be any serious blockers for this?

**Comment by BewareMyPower** [comment]
> I don't think there should be any serious blockers

Actually yes. The CMakeLists.txt needs some fixes. I was working on this issue a few days ago and will continue the fix after backing to work. The core issue is about the static linking. 

Here is my working branch: https://github.com/BewareMyPower/pulsar/commits/bewaremypower/cpp-static-link. Please note that it doesn't work currently (I forgot to push latest commits in my Windows laptop).
1. The binary suffix should be `.pyd` on Windows (in my branch it's `.dll`, which is wrong)
2. The Python library should not be linked statically when building `_pulsar.pyd`.
