### ISSUE TITLE
[feature request] release built distributions for python 3.11

### ISSUE THREAD

**Issue by bpereto** [apache/pulsar-client-python#75]
# Motivation

Currently there are only build distributions released on pypi.org for up to python 3.10.
Release built distributions to use the pulsar client in python 3.11

https://pypi.org/project/pulsar-client/#files

**Comment by curtiscook** [comment]
Can we automate the addition of new python releases? This should fix 3.11, but 3.12 is already around the corner

**Comment by merlimat** [comment]
@curtiscook The build process is all automated in GitHub actions. It's very simple to add new Python versions. Take a look at #83

**Comment by merlimat** [comment]
Once the Python 3.12 is supported by Manylinux images (https://github.com/pypa/manylinux), we can already include it in the builds

**Comment by curtiscook** [comment]
> Once the Python 3.12 is supported by Manylinux images (https://github.com/pypa/manylinux), we can already include it in the builds

This is great, the worry is we don't add support until someone notices and releases have a decent gap in-between. Maybe we can just be more disciplined about adding support?
