### ISSUE TITLE
[feature request] Reader support seek by timestamp.

### ISSUE THREAD

**Issue by shibd** [apache/pulsar-client-python#78]
## Motivation

CPP client already supported, In python client, just need wrapper it.

**Comment by haphut** [comment]
I am confused why this was opened. There has been a test for seeking by timestamp for a while: https://github.com/apache/pulsar-client-python/blame/8c36eb70f981c6cc1dec7691c7ab759a5520204d/tests/pulsar_test.py#L1001 .

Though the `time.sleep(0.5)` right after looks questionable. Do we have to guess when the seek is finished before attempting to read?

**Comment by shibd** [comment]
> I am confused why this was opened. There has been a test for seeking by timestamp for a while:

You are right. I missed it.

> Though the time.sleep(0.5) right after looks questionable. Do we have to guess when the seek is finished before attempting to read?

I think not. It is a sync method. I push a PR to remove sleep.

**Comment by haphut** [comment]
Fantastic. Thank you!
