### ISSUE TITLE
Pulsar Version 3.0.0 on https://pypi.org/project/pulsar-client/

### ISSUE THREAD

**Issue by astifter** [apache/pulsar-client-python#82]
Hi,

you are publishing a verion 3.0.0 that is not correlated to the actual Pulsar versioning, is that on purpose? I have had a hard time tracking down issues because of this.

Andreas

**Comment by merlimat** [comment]
@astifter The C++ and Python clients have been pulled out of the main Pulsar release cycle. The versions of these clients are now independent.
