### ISSUE TITLE
Producer.sendAsync hangs if rate is high enough

### ISSUE THREAD

**Issue by BoillMan133** [apache/pulsar-client-python#94]
Used:
python: 3.9.6
pulsar-client       3.0.0
Pulsar: docker on localhost of apachepulsar/pulsar:2.11.0

Just made a simple script that sendsAsync thousand messages (Strings) in a for loop. 
And script at some point just hangs. No any errors in log or in a callbacks or anything. 
Doesn't matter if flag `block_if_queue_full` is set or no, or what `max_pending_messages` or `batching_max_messages` are. 
Slowing down a client helps (Introducing artifical pauses, or often flush())

Never seen that in a java client.

**Comment by hyperevo** [comment]
Pretty sure this is fixed in 3.0.1. https://github.com/apache/pulsar-client-python/pull/87

**Comment by BoillMan133** [comment]
> Pretty sure this is fixed in 3.0.1. #87

Thanks for an update. Do you know when 3.0.1 planned to be released ?

**Comment by BewareMyPower** [comment]
@BoillMan133 The 3.1.0 candidate 4 is voting currently, if there is nothing wrong we can have it in PyPI next week: https://lists.apache.org/thread/lyzyyg9yhwc836trv0dhdgq23bym4som
